settings:
  commit:
    templates:
      create: "content(create): {path}"
      update: "content(update): {path}"
      delete: "content(delete): {path}"
      rename: "content(rename): {oldPath} -> {newPath}"
media:
  - name: media
    label: media
    input: public/uploads
    output: /uploads
  - name: website
    input: public/resources
    output: /web-resources
content:
  - name: schedules
    label: Horaires
    type: file
    path: src/_data/schedules.json
    fields:
      - name: section
        type: reference
        options:
          collection: disciplines
          value: "{fields.name}"
          label: "{fields.name}"
      - { name: monday, label: lundi, type: string}
      - { name: tuesday, label: mardi, type: string}
      - { name: wednesday, label: mercredi, type: string}
      - { name: thursday, label: jeudi, type: string}
      - { name: friday, label: vendredi, type: string}
      - { name: saturday, label: samedi, type: string}
      - { name: sunday, label: dimanche, type: string}
      - { name: comment, label: Commentaire, type: string}
  - name: footer
    label: Bas-de-page
    type: file
    path: src/_data/footer.json
    fields:
      - name: other-websites
        label: Sites web affiliés
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{label} {url} ({index})"
        fields:
          - name: label
            type: string
          - name: url
            type: string
  - name: dojo
    label: Le Dojo
    type: file
    path: src/content/dojo.md
    view:
      fields: [ name ]
    fields:
      - { name: name, label: Nom, type: string, required: false }
      - { name: body-1, label: section-1, type: rich-text, required: false }
      - { name: side-image, label: Illustration, type: image, required: false }
      - { name: body-2, label: section-2, type: rich-text, required: false }
      - { name: body-3, label: section-3, type: rich-text, required: false }
      - { name: body, label: bodyi, type: rich-text, required: false }
  - name: disciplines
    label: Sections
    type: collection
    path: src/content/disciplines
    view:
      fields: [ name, draft ]
    fields:
      - { name: name, label: Nom, type: string, required: true }
      - { name: slug, label: Slug, type: string }
      - { name: logo, label: Logo, type: image }
      - { name: summary, label: Description, type: string }
      - { name: contact, label: Contact, type: string }
      - { name: schedule, label: Horaires, type: string }
      - { name: body, label: Contenu, type: rich-text }
      - { name: draft, label: Brouillon, type: boolean }
  - name: sign-up
    label: Inscriptions
    type: file
    path: src/_data/resources.json
    fields:
      - name: pdf
        label: >
          Sélectionner le PDF d'inscription
        type: file
        options:
          path: public/uploads/inscriptions
          extensions: [pdf]
  - name: events
    label: Évènements
    type: collection
    path: src/content/events
    view:
      fields: [ title, pubDatetime ]
    fields:
      - { name: title, label: Titre, type: string, required: true }
      - { name: pubDate, label: Date, type: date }
      - { name: modDate, label: Date, type: date }
      - { name: slug, label: Slug, type: string }
      - { name: draft, label: Brouillon, type: boolean }
      - { name: description, label: Description, type: string }
      - { name: body, label: Contenu, type: rich-text }
  - name: articles
    label: Articles
    type: collection
    path: src/content/articles
    view:
      fields: [ title, draft, pubDatetime ]
    fields:
      - { name: author, label: Auteur, type: string, required: true }
      - name: pubDate
        label: Date de publication
        type: date
        default: ""
        required: true
      - { name: title, label: Titre, type: string, required: true }
      - { name: draft, label: Mode brouillon, type: boolean }
      - { name: tags, label: Étiquettes, type: string, list: true }
      - { name: description, label: Description, type: string}
      - { name: image, label: Illustration, type: image, required: true}
      - { name: body, label: Contenu, type: rich-text, required: true }