settings:
  commit:
    templates:
      create: "content(create): {path}"
      update: "content(update): {path}"
      delete: "content(delete): {path}"
      rename: "content(rename): {oldPath} -> {newPath}"
media:
  - name: images
    label: Images
    input: public/uploads
    output: /uploads
    categories: [image]
    rename: safe
  - name: documents
    label: Documents
    input: public/uploads
    output: /uploads
    categories: [document]
    rename: safe
content:
  - name: config
    label: Configuration du site web
    type: file
    path: src/_data/conf.json
    fields:
    - name: home
      label: Accueil
      fields:
        - name: schedules
          label: Horaires
          type: object
          list:
            collapsible:
              collapsed: true
              summary: "{section}"
          fields:
            - name: section
              type: reference
              label: Section
              options:
                collection: disciplines
                value: "{fields.name}"
                label: "{fields.name}"
            - { name: content, label: Contenu, type: rich-text}
            - { name: comment, label: Commentaire, type: string}
    - name: footer
      label: Bas-de-page
      type: object
      fields:
        - name: addresses
          label: Adresses web affiliées
          type: object
          fields:
            - name: dojo
              label: Dojo
              type: string
              required: true
            - name: headquarters
              label: Siège social
              type: string
              required: true
        - name: other-websites
          label: Sites web affiliés
          type: object
          list:
            collapsible:
              collapsed: true
              summary: "{label} / {url}"
          fields:
            - name: label
              type: string
              required: true
            - name: url
              type: string
              required: true
        - name: links
          label: Liens utiles
          type: object
          list:
            collapsible:
              collapsed: true
              summary: "{label} / {url}"
          fields:
            - name: label
              type: string
              required: true
            - name: url
              type: string
              required: true
        - name: facebook-link
          label: Lien Facebook
          type: string
        - name: instagram-link
          label: Lien Instagram
          type: string
        - name: youtube-link
          label: Lien Youtube
          type: string
  - name: staff
    label: Staff
    type: collection
    path: src/content/staff
    view:
      fields: [ name, photo ]
    fields:
      - { name: name, label: Nom, type: string, required: true }
      - { name: jobTitle, label: Fonction, type: string, required: true }
      - { name: photo, type: image }
      - { name: email, type: string }
      - { name: tel, type: string }
      - { name: bio,type: rich-text}
  - name: dojo
    label: Le Dojo
    type: file
    path: src/content/dojo.md
    fields:
      - { name: body-1, label: section-1, type: rich-text, required: false }
      - { name: side-image, label: Illustration, type: image, required: false }
      - { name: body-2, label: section-2, type: rich-text, required: false }
      - { name: body-3, label: section-3, type: rich-text, required: false }
  - name: disciplines
    label: Sections
    type: collection
    path: src/content/disciplines
    view:
      fields: [ name, logo, coordinator, draft ]
    fields:
      - { name: name, label: Nom, type: string, required: true }
      - { name: draft, label: Brouillon, type: boolean, default: true }
      - { name: slug, label: Slug, type: string }
      - { name: logo, label: Logo, type: image }
      - { name: summary, label: Description, type: string, required: true }
      - name: coordinator
        label: Coordinateur
        type: reference
        options:
          collection: staff
          required: true
          value: "{fields.name}"
          label: "{fields.name}"
      - { name: body, label: Contenu, type: rich-text }
  - name: sign-up
    label: Inscriptions
    type: file
    path: src/_data/resources.json
    fields:
      - name: pdf
        label: >
          Sélectionner le PDF d'inscription
        type: file
        options:
          media: documents
          path: public/uploads/inscriptions
          extensions: [pdf]
          required: true
  - name: events
    label: Évènements
    type: collection
    path: src/content/events
    view:
      fields: [ title, image, startDate , endDate, location, draft]
    fields:
      - { name: title, label: Titre, type: string, required: true }
      - { name: draft, label: Brouillon, type: boolean, default: true }
      - { name: startDate, label: Date de début, type: date, required: true}
      - { name: endDate, label: Date de fin, type: date, default: ""}
      - { name: location, label: Lieu, type: string }
      - { name: description, label: Description, type: string }
      - { name: image, label: Illustration, type: image, required: true}
      - name: registrationLink
        label: > 
          Lien d'un formulaire
      - { name: body, label: Contenu, type: rich-text }
  - name: articles
    label: Articles
    type: collection
    path: src/content/articles
    view:
      fields: [ title, image, pubDate, draft]
    fields:
      - { name: author, label: Auteur, type: string, required: true }
      - name: pubDate
        label: Date de publication
        type: date
        default: ""
        required: true
      - { name: title, label: Titre, type: string, required: true }
      - { name: draft, label: Mode brouillon, type: boolean, default: true }
      - { name: tags, label: Étiquettes, type: string, list: true }
      - { name: description, label: Description, type: string}
      - { name: image, label: Illustration, type: image, required: true}
      - { name: body, label: Contenu, type: rich-text, required: true }